test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: ruby_forum_test
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: ruby_forum_development
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432